main: net.tfminecraft.VehicleFramework.VehicleFramework
api-version: 1.20
name: VehicleFramework
version: 1.0.4
author: Drefvelin
folia-supported: true

depend: [NBTAPI, ModelEngine, ProtocolLib, TLibs]
softdepend: [MythicMobs, CoreProtect]

commands:
  vf:
    useage: /<command>
    description: Vehicle Framework Command